version: "3.8"
services:
  sync_app:
    build: .
    volumes:
      - ./clients:/app/clients
    environment:
      # Variáveis genéricas (opcional, pode ser definido no Dockerfile)
      PYTHONUNBUFFERED: 1